name: Build

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 22.4
        uses: actions/setup-node@v3
        with:
          node-version: '22.4'
          architecture: 'arm64'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright dependencies
        run: pnpx playwright install --with-deps chromium

      - name: Lint
        run: pnpm run lint

      - name: Build application
        run: pnpm run build

      - name: Install make
        run: sudo apt-get install -y make

      - name: Package the app as docker image
        run: |
          make build
          docker images
