# Workflow to create and publish Docker image on version tags
name: Release Docker Image

# 1. Input/Trigger Configuration
# 1.1 Define workflow triggers
on:
  # 1.1.1 Trigger on version tags
  push:
    tags:
      - 'v*.*.*'
  # 1.1.2 Allow manual trigger
  workflow_dispatch:

# 1.2 Define environment variables
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/wuchuheng/com.timecheck.device

# 2. Job Configuration
jobs:
  # 2.1 Release job definition
  release:
    # 2.1.1 Set runner environment
    runs-on: ubuntu-24.04-arm

    # 2.2 Set permissions
    permissions:
      contents: read
      packages: write

    # 2.3 Define release steps
    steps:
      # 2.3.1 Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2.3.2 Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 2.3.3 Login to Container registry
      - name: Login to Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          make build
          docker images
          
          # Use environment variable with tag
          IMAGE_NAME=ghcr.io/wuchuheng/com.timecheck.device:${{ github.ref_name }}
          docker tag com.timecheck.device:latest-arm64 ${IMAGE_NAME}
          docker push ${IMAGE_NAME}
